/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xestionclinica.vista;

import Utils.PoliticaFocus;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import xestionclinica.controlador.Coordinador;
import xestionclinica.modelo.CanVo;
import xestionclinica.modelo.PropietarioVo;
import xestionclinica.modelo.RazaVo;

/**
 *
 * @author hugolg
 */
public class InternalCansRazas extends javax.swing.JInternalFrame {

    private Coordinador coordinador;
    private static final int CARD_CAN = 0;
    private static final int CARD_RAZA = 1;
    private static int ACTUAL;

    private CardLayout cardLayout;
    private PoliticaFocus pFocusCan,pFocusRaza;

   
    public InternalCansRazas(Coordinador coordinador) {
        initComponents();
        this.coordinador = coordinador;        
        ACTUAL = CARD_CAN;
        cardLayout = (CardLayout) pnlCard.getLayout();
        lstPropietarios.setModel(coordinador.getListPropietarios());
        lstRazas.setModel(coordinador.getListRazas());
        setPoliticaFocus();
        aplicarPoliticaFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlCombo = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        lblAlta = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        jcbAltaDe = new javax.swing.JComboBox<>();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        pnlCard = new javax.swing.JPanel();
        pnlAltaCan = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNomeCan = new javax.swing.JTextField();
        lblRazas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRazas = new javax.swing.JList<>();
        lblChip = new javax.swing.JLabel();
        txtChip = new javax.swing.JTextField();
        lblPropietarios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPropietarios = new javax.swing.JList<>();
        pnlAltaRaza = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        lblRaza = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        txtRaza = new javax.swing.JTextField();
        pnlBtn = new javax.swing.JPanel();
        btnGardar = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        btnPechar = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        pnlCombo.setMaximumSize(new java.awt.Dimension(32841, 40));
        pnlCombo.setMinimumSize(new java.awt.Dimension(130, 40));
        pnlCombo.setPreferredSize(new java.awt.Dimension(130, 40));
        pnlCombo.setLayout(new javax.swing.BoxLayout(pnlCombo, javax.swing.BoxLayout.LINE_AXIS));
        pnlCombo.add(filler1);

        lblAlta.setText("Realizar alta de");
        pnlCombo.add(lblAlta);
        pnlCombo.add(filler2);

        jcbAltaDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cans", "Razas" }));
        jcbAltaDe.setMaximumSize(new java.awt.Dimension(32767, 27));
        jcbAltaDe.setMinimumSize(new java.awt.Dimension(56, 27));
        jcbAltaDe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAltaDeItemStateChanged(evt);
            }
        });
        pnlCombo.add(jcbAltaDe);
        pnlCombo.add(filler3);

        getContentPane().add(pnlCombo, java.awt.BorderLayout.NORTH);

        pnlCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlCard.setLayout(new java.awt.CardLayout());

        pnlAltaCan.setLayout(new java.awt.GridBagLayout());

        lblNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAltaCan.add(lblNome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAltaCan.add(txtNomeCan, gridBagConstraints);

        lblRazas.setText("Razas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAltaCan.add(lblRazas, gridBagConstraints);

        lstRazas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstRazas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAltaCan.add(jScrollPane1, gridBagConstraints);

        lblChip.setText("Chip");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAltaCan.add(lblChip, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAltaCan.add(txtChip, gridBagConstraints);

        lblPropietarios.setText("Propietarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAltaCan.add(lblPropietarios, gridBagConstraints);

        lstPropietarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstPropietarios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlAltaCan.add(jScrollPane2, gridBagConstraints);

        pnlCard.add(pnlAltaCan, "can");

        pnlAltaRaza.setLayout(new javax.swing.BoxLayout(pnlAltaRaza, javax.swing.BoxLayout.LINE_AXIS));
        pnlAltaRaza.add(filler4);

        lblRaza.setText("Raza");
        lblRaza.setAlignmentY(0.0F);
        lblRaza.setMaximumSize(new java.awt.Dimension(34, 27));
        lblRaza.setMinimumSize(new java.awt.Dimension(34, 27));
        pnlAltaRaza.add(lblRaza);
        pnlAltaRaza.add(filler5);

        txtRaza.setAlignmentY(0.0F);
        txtRaza.setMaximumSize(new java.awt.Dimension(2147483647, 27));
        txtRaza.setMinimumSize(new java.awt.Dimension(6, 27));
        pnlAltaRaza.add(txtRaza);

        pnlCard.add(pnlAltaRaza, "raza");

        getContentPane().add(pnlCard, java.awt.BorderLayout.CENTER);

        pnlBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlBtn.setLayout(new javax.swing.BoxLayout(pnlBtn, javax.swing.BoxLayout.Y_AXIS));

        btnGardar.setText("Gardar");
        btnGardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGardarActionPerformed(evt);
            }
        });
        pnlBtn.add(btnGardar);
        pnlBtn.add(filler6);

        btnPechar.setText("Pechar");
        btnPechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPecharActionPerformed(evt);
            }
        });
        pnlBtn.add(btnPechar);

        getContentPane().add(pnlBtn, java.awt.BorderLayout.EAST);

        setBounds(0, 0, 646, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAltaDeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAltaDeItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (jcbAltaDe.getSelectedIndex() == 0) {
                cardLayout.show(pnlCard, "can");
                ACTUAL = CARD_CAN;
                super.setTitle("Novo can");
                aplicarPoliticaFocus();
            } else {
                cardLayout.show(pnlCard, "raza");                
                ACTUAL = CARD_RAZA;
                super.setTitle("Nova raza");
                aplicarPoliticaFocus();
            }
        }
    }//GEN-LAST:event_jcbAltaDeItemStateChanged

    private void btnGardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGardarActionPerformed
        // TODO add your handling code here:
        if (ACTUAL == CARD_CAN) {
            altaCan();
        } else {
            altaRaza();
        }
    }//GEN-LAST:event_btnGardarActionPerformed

    private void btnPecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnPecharActionPerformed

    private void setPoliticaFocus(){
        pFocusCan = new PoliticaFocus();
        pFocusCan.añadirComponent(jcbAltaDe);
        pFocusCan.añadirComponent(txtNomeCan);
        pFocusCan.añadirComponent(txtChip);
        pFocusCan.añadirComponent(lstRazas);
        pFocusCan.añadirComponent(lstPropietarios);                       
        
        pFocusRaza = new PoliticaFocus();
        pFocusRaza.añadirComponent(jcbAltaDe);
        pFocusRaza.añadirComponent(txtRaza);
    }
    
    private void aplicarPoliticaFocus(){
        if(ACTUAL == CARD_CAN){
            this.setFocusTraversalPolicy(pFocusCan);
        }else{
            this.setFocusTraversalPolicy(pFocusRaza);
        }
    }
    
    private void altaCan() {
        if (coordinador.altaCan(this, getCanFormulario())) {
            this.dispose();
        }
    }

    private CanVo getCanFormulario() {
        CanVo resultado = new CanVo();
        resultado.setNome(txtNomeCan.getText().trim());
        resultado.setChip(txtChip.getText().trim());
        try {
            resultado.setCodRaza(lstRazas.getModel().getElementAt(lstRazas.getSelectedIndex()).getId());
        } catch (Exception e1) {
            resultado.setCodRaza(0);
        }
        try {
            resultado.setDniPropietario(lstPropietarios.getModel().getElementAt(lstPropietarios.getSelectedIndex()).getDni());
        } catch (Exception e2) {
            resultado.setDniPropietario("");
        }
        return resultado;
    }

    private void altaRaza() {
        if (coordinador.altaRaza(this, new RazaVo(txtRaza.getText().trim()))) {
            this.dispose();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGardar;
    private javax.swing.JButton btnPechar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbAltaDe;
    private javax.swing.JLabel lblAlta;
    private javax.swing.JLabel lblChip;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPropietarios;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblRazas;
    private javax.swing.JList<PropietarioVo> lstPropietarios;
    private javax.swing.JList<RazaVo> lstRazas;
    private javax.swing.JPanel pnlAltaCan;
    private javax.swing.JPanel pnlAltaRaza;
    private javax.swing.JPanel pnlBtn;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlCombo;
    private javax.swing.JTextField txtChip;
    private javax.swing.JTextField txtNomeCan;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables

}
