/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xestionclinica.vista;

import xestionclinica.controlador.Coordinador;

/**
 *
 * @author hugolg
 */
public class VistaXestion extends javax.swing.JFrame {

    private Coordinador coordinador;
    
    public VistaXestion() {
        super.setTitle("Xestion clinica");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOpcions = new javax.swing.JMenu();
        mnuAltas = new javax.swing.JMenu();
        mnuiCansRazas = new javax.swing.JMenuItem();
        mnuiPropietarios = new javax.swing.JMenuItem();
        mnuiVacinacions = new javax.swing.JMenuItem();
        mnuiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuOpcions.setText("Opcións");

        mnuAltas.setText("Altas");

        mnuiCansRazas.setText("Cans/Razas");
        mnuiCansRazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCansRazasActionPerformed(evt);
            }
        });
        mnuAltas.add(mnuiCansRazas);

        mnuiPropietarios.setText("Propietarios");
        mnuiPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiPropietariosActionPerformed(evt);
            }
        });
        mnuAltas.add(mnuiPropietarios);

        mnuOpcions.add(mnuAltas);

        mnuiVacinacions.setText("Xestión vacinacións");
        mnuiVacinacions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiVacinacionsActionPerformed(evt);
            }
        });
        mnuOpcions.add(mnuiVacinacions);

        mnuiSair.setText("Saír");
        mnuiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiSairActionPerformed(evt);
            }
        });
        mnuOpcions.add(mnuiSair);

        jMenuBar1.add(mnuOpcions);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void mnuiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuiSairActionPerformed

    private void mnuiCansRazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCansRazasActionPerformed
        // TODO add your handling code here:
        coordinador.abrirInternalCansRazas();
    }//GEN-LAST:event_mnuiCansRazasActionPerformed

    private void mnuiPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiPropietariosActionPerformed
        // TODO add your handling code here:
        coordinador.abrirInternalPropietarios();
    }//GEN-LAST:event_mnuiPropietariosActionPerformed

    private void mnuiVacinacionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiVacinacionsActionPerformed
        // TODO add your handling code here:
        coordinador.abrirInternalVacinacions();
    }//GEN-LAST:event_mnuiVacinacionsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuAltas;
    private javax.swing.JMenu mnuOpcions;
    private javax.swing.JMenuItem mnuiCansRazas;
    private javax.swing.JMenuItem mnuiPropietarios;
    private javax.swing.JMenuItem mnuiSair;
    private javax.swing.JMenuItem mnuiVacinacions;
    // End of variables declaration//GEN-END:variables

    public void setCoordinador(Coordinador miCoordinador) {
        this.coordinador = miCoordinador;
    }
}
