package xestionclinica.vista;

import Utils.PoliticaFocus;
import javax.swing.JFrame;
import xestionclinica.controlador.Coordinador;

public class VistaInicioSesion extends JFrame {
    
    private Coordinador coordinador;

    /**
     * Creates new form VistaUsuario
     */
    public VistaInicioSesion() {
        initComponents();
        super.setTitle("Validación de usuario");
        setPoliticaFocus();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pblCentro = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasinal = new javax.swing.JLabel();
        txtContrasinal = new javax.swing.JTextField();
        lblIp = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        lblPorto = new javax.swing.JLabel();
        txtPorto = new javax.swing.JTextField();
        pnlBottom = new javax.swing.JPanel();
        btnConectar = new javax.swing.JButton();
        btnPechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pblCentro.setLayout(new java.awt.GridBagLayout());

        lblUsuario.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pblCentro.add(lblUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pblCentro.add(txtUsuario, gridBagConstraints);

        lblContrasinal.setText("Contrasinal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pblCentro.add(lblContrasinal, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pblCentro.add(txtContrasinal, gridBagConstraints);

        lblIp.setText("IP Servidor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pblCentro.add(lblIp, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pblCentro.add(txtIp, gridBagConstraints);

        lblPorto.setText("Porto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pblCentro.add(lblPorto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pblCentro.add(txtPorto, gridBagConstraints);

        getContentPane().add(pblCentro, java.awt.BorderLayout.CENTER);

        pnlBottom.setPreferredSize(new java.awt.Dimension(0, 50));
        pnlBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        pnlBottom.add(btnConectar);

        btnPechar.setText("Pechar");
        btnPechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPecharActionPerformed(evt);
            }
        });
        pnlBottom.add(btnPechar);

        getContentPane().add(pnlBottom, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(436, 241));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        // TODO add your handling code here:
        //conectarBD();
        coordinador.iniciarSesion(txtIp.getText().trim(), txtUsuario.getText().trim(), txtContrasinal.getText().trim(), txtPorto.getText().trim());
    }//GEN-LAST:event_btnConectarActionPerformed

    private void btnPecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPecharActionPerformed
        // TODO add your handling code here:
        coordinador.cerrarInicioSesion();
    }//GEN-LAST:event_btnPecharActionPerformed
     
    private void setPoliticaFocus(){
        PoliticaFocus pFocus = new PoliticaFocus();
        pFocus.añadirComponent(txtUsuario);
        pFocus.añadirComponent(txtContrasinal);
        pFocus.añadirComponent(txtIp);
        pFocus.añadirComponent(txtPorto);
        this.setFocusTraversalPolicy(pFocus);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnPechar;
    private javax.swing.JLabel lblContrasinal;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblPorto;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pblCentro;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JTextField txtContrasinal;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtPorto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void setCoordinador(Coordinador miCoordinador) {
        this.coordinador = miCoordinador;
    }
}
